config = {
    'backbone_name' : 'swin_v2_t',
    'head_name' : 'adaface',
    'embedding_dim' : 512,
    'margin' : 0.4,
    'scale' : 64,
    'h' : 0.333,
    't_alpha' : 0.99,
    'optimizer' : 'adamw',
    'learning_rate' : 5e-4,
    'start_factor' : 1e-3,
    'min_lr' : 5e-6,
    'weight_decay' : 0.05,
    'gradient_clip_val' : 1.0,
    'gradient_clip_algorithm' : 'norm',
    'scheduler' : 'cosine',
    'max_epochs' : 32,
    'warmup_epochs' : 3,
    'batch_size' : 320,
    'precision': 'bf16-mixed',
    'dataset_name': 'MS1MV2',
    'val_datasets' : ['CALFW', 'CPLFW'],
    'num_workers' : 8,
    'crop_prob' : 0.2,
    'low_res_prob' : 0.2,
    'photometric_prob' : 0.2
}