import os
config = {
    'backbone_name' : 'davit_t',
    'pretrained_backbone_path' : os.path.join('data', 'models', 'davit_t_adaface_MS1MV2_Dataset', 'backbone.pth'),
    'pretrained_face_recognition_path' : os.path.join('data', 'models', 'davit_t_adaface_MS1MV2_Dataset', 'recognition_subnet.pth'),
    'resume_from_checkpoint' : os.path.join('checkpoints', 'multitask_training_test_davit', 'model.pth'),
    'head_type' : 'adaface',
    'embedding_dim' : 512,
    'margin' : 0.4,
    'scale' : 64,
    'h' : 0.333,
    't_alpha' : 0.99,
    'optimizer' : 'adamw',
    'learning_rate' : 1e-3,
    'start_factor' : 1e-1,
    'min_lr' : 5e-6,
    'weight_decay' : 0.05,
    'scheduler' : 'cosine',
    'max_epochs' : 24,
    'warmup_epochs' : 4,
    'freeze_backbone_epochs' : 2,
    'batch_size' : 320,
    'min_num_images_per_class' : 20,
    'num_workers' : 8,
}