import os
config = {
    'output_folder_name' : 'multitask_swinv2_t_face_emotion_age_gender_race_attribute_pose_standard',
    'backbone_name' : 'swin_v2_t',
    'pretrained_backbone_path' : os.path.join('data', 'models', 'swin_v2_t_adaface_MS1MV2', 'backbone.pth'),
    'pretrained_face_recognition_subnet_path' : os.path.join('data', 'models', 'swin_v2_t_adaface_MS1MV2', 'recognition_subnet.pth'),
    'pretrained_margin_head_path' : os.path.join('data', 'models', 'swin_v2_t_adaface_MS1MV2', 'margin_head.pth'),
    'multiscale_fusion_type' : 'standard', # can be either 'standard' or 'light' for now.
    'head_type' : 'adaface',
    'embedding_dim' : 512,
    'margin' : 0.4,
    'scale' : 64,
    'h' : 0.333,
    't_alpha' : 0.99,
    'optimizer' : 'adamw',
    'learning_rate' : 5e-4,
    'backbone_lr_multiplier' : 1.0/10.0,
    'start_factor' : 1e-1,
    'min_lr' : 5e-6,
    'weight_decay' : 0.05,
    'gradient_clip_val' : 1.0,
    'scheduler' : 'cosine',
    'max_epochs' : 64,
    'epoch_size' : 1_000_000,
    'warmup_epochs' : 3,
    'freeze_backbone_epochs' : 2,
    'batch_size' : 192,
    'precision' : 'bf16-mixed',
    'num_workers' : 8,
}