import os
config = {
    'output_folder_name' : 'multitask_davit_s_face_emotion_age_gender_race',
    'backbone_name' : 'davit_s',
    'pretrained_backbone_path' : os.path.join('data', 'models', 'davit_s_adaface_MS1MV2', 'backbone.pth'),
    'pretrained_face_recognition_subnet_path' : os.path.join('data', 'models', 'davit_s_adaface_MS1MV2', 'recognition_subnet.pth'),
    'pretrained_margin_head_path' : os.path.join('data', 'models', 'davit_s_adaface_MS1MV2', 'margin_head.pth'),
    'head_type' : 'adaface',
    'embedding_dim' : 512,
    'margin' : 0.4,
    'scale' : 64,
    'h' : 0.333,
    't_alpha' : 0.99,
    'optimizer' : 'adamw',
    'learning_rate' : 5e-4,
    'backbone_lr_multiplier' : 1.0/20.0,
    'start_factor' : 1e-1,
    'min_lr' : 5e-6,
    'weight_decay' : 0.05,
    'gradient_clip_val' : 1.0,
    'scheduler' : 'cosine',
    'max_epochs' : 24,
    'epoch_size' : 2_500_000,
    'warmup_epochs' : 5,
    'freeze_backbone_epochs' : 3,
    'batch_size' : 240,
    'precision' : 'bf16-mixed',
    'num_workers' : 8,
}