config = {
    'backbone_name' : 'davit_t',
    'resume_from_checkpoint' : None,
    'head_name' : 'adaface',
    'embedding_dim' : 512,
    'margin' : 0.4,
    'scale' : 64,
    'h' : 0.333,
    't_alpha' : 0.99,
    'optimizer' : 'adamw',
    'learning_rate' : 1e-3,
    'start_factor' : 1e-1,
    'min_lr' : 1e-6,
    'weight_decay' : 0.05,
    'scheduler' : 'cosine',
    'max_epochs' : 24,
    'warmup_epochs' : 3,
    'batch_size' : 320,
    'precision': '16-mixed',
    'dataset_name': 'MS1MV2_Dataset',
    'val_datasets' : ['LFW_Dataset', 'CALFW_Dataset', 'CPLFW_Dataset'],
    'min_num_images_per_class' : 20,
    'num_workers' : 8,
    'crop_prob' : 0.2,
    'low_res_prob' : 0.2,
    'photometric_prob' : 0.2
}