python pretrain.py \
    --backbone_name ir_18 \
    --head_name adaface \
    --embedding_dim 512 \
    --margin 0.4 \
    --scale 64 \
    --optimizer adamw \
    --learning_rate 5e-4 \
    --weight_decay 0.05 \
    --scheduler cosine \
    --max_epochs 120 \
    --warmup_epochs 5 \
    --batch_size 512 \
    --dataset_name CasiaWebFace_Dataset \
    --val_datasets LFW_Dataset CALFW_Dataset CPLFW_Dataset \
    --num_workers 8 \
