python pretrain.py \
    --backbone_name swin_v2_t \
    --head_name adaface \
    --embedding_dim 512 \
    --margin 0.4 \
    --scale 64 \
    --optimizer adamw \
    --learning_rate 5e-4 \
    --start_factor 1e-3 \
    --min_lr 5e-6 \
    --weight_decay 0.05 \
    --scheduler cosine \
    --max_epochs 60 \
    --warmup_epochs 5 \
    --batch_size 512 \
    --precision 16-mixed \
    --dataset_name VGGFace_Dataset \
    --val_datasets LFW_Dataset CALFW_Dataset CPLFW_Dataset \
    --num_workers 8 \
    --crop_prob 0.1 \
    --low_res_prop 0.1 \
    --photometric_prop 0.1
